[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,NEXT_PUBLIC_CLERK_SIGN_IN_URL,NEXT_PUBLIC_CLERK_SIGN_UP_URL,NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,NEXT_PUBLIC_APP_URL,RAZORPAY_KEY_ID,RAZORPAY_WEBHOOK_SECRET,CLERK_ENCRYPTION_KEY,RAZORPAY_KEY_SECRET,CLERK_SECRET_KEY,OPENROUTER_API_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"